### ISSUE TITLE
Replace standard burner-wallet balances with CO2, Goellars and Trees

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#2]
## Scope

- Currently the burner-wallet features three crypto currencies DAI, ETH, PDAI
- In the "Planet A" game, we'd like to replace the above currencies with three new "assets":
  - Goellars: The in game currency that functions as a "virtual dollar"
  - CO2: An asset that describes the amount a player decided to externalize their cost
  - Plants: An asset that describes the amount a player decided to offset their external cost ("Planting trees reduces CO2")
- We're not planning to run the game at the Ethereum meetup on mainnet! Instead we're aiming for the LeapDAO test network.
- Goellars and CO2 are not exchangeable (so there's no need for an "Exchange.js" integration")
- Goellars, CO2 are already registered as LeapDAO test network tokens. Their colors can be found here: https://testnet.leapdao.org/registerToken
- As neither Goellars nor CO2 are intended to be exited from Plasma, there's also no need to have any ETH in the wallet. Hence the ETH balance can be hidden too

Examples where e.g. PDAI is used as the default currency but should be replaced with Goellars:

<img width="755" alt="Screen Shot 2019-07-16 at 14 05 19" src="https://user-images.githubusercontent.com/2758453/61292943-d5982700-a7d2-11e9-95ee-7cf2df4fedae.png">
<img width="750" alt="Screen Shot 2019-07-16 at 14 05 08" src="https://user-images.githubusercontent.com/2758453/61292944-d5982700-a7d2-11e9-829f-0055a46d74e2.png">
<img width="758" alt="Screen Shot 2019-07-16 at 14 05 02" src="https://user-images.githubusercontent.com/2758453/61292946-d5982700-a7d2-11e9-9fe7-2b0be00a851e.png">

## Deliverables

- Replace DAI, ETH, PDAI balances with Goellars, Plants and CO2 in App.js
- Make sure that *only* Goellars are transferrable in the UI between users. Plants and CO2 are not supposed to be transferrable
- Adjust the balance of Goellars in other places too e.g. SendToAddress.js and others

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
~why replace `DAI and ETH`?~
read the above argumentation, agree.

 i would only replace pDAI with goellars:
- don't see a reason to display CO2, because users never hold CO2, only earth and air contract
- don't see a reason to display trees. what should people do about them? trade?

instead there is a passport NFT that each user has (containing cumulative `co2Locked` and `co2Emitted`. why not use the badge display for that information, like in the Motion wallet:

<img width="731" alt="Screen Shot 2019-07-16 at 7 53 17 PM" src="https://user-images.githubusercontent.com/659301/61317749-ef059700-a803-11e9-8f02-897b404fa344.png">

the people can click their passport and see information about their own statistics and their country.
