### ISSUE TITLE
Display the global CO2 value and make the CO2 "run-away point" configurable

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#3]
## Scope

<img width="966" alt="Screen Shot 2019-07-16 at 14 08 47" src="https://user-images.githubusercontent.com/2758453/61293115-40496280-a7d3-11e9-864f-541f1f19ffd3.png">

- For every trade that occurs in the game, an amount of CO2 is emitted into the "Air"
- With proceeding pollution of the "Air", living conditions become tougher
- A "run-away" point or "point of no return" is a situation that occurs when there has been so much CO2 emitted, that planing plants/trees becomes less efficient to lessen the CO2 impact
- In this sense, a "run-away" point marks the beginning of a potential death spiral

## Deliverables

<img width="615" alt="Screen Shot 2019-07-16 at 14 13 11" src="https://user-images.githubusercontent.com/2758453/61293391-de3d2d00-a7d3-11e9-9ae4-5da2f59c4ad9.png">

- Read the global CO2 value from all the unspents and display its value in a [dramatic](https://www.mcc-berlin.net/de/forschung/co2-budget.html) way in the UI. Ideally on the main view App.js
- Note that for the purpose of testing the game at the Ethereum Meetup, a complicated time-series data plot/chart is **not** required! It's something we can build for ETHBerlinZwei of course. As a countdown requires similar functionality, we recommend **not** implementing that either (too much work for now).

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
and then there was this crazy idea: https://leapdao.slack.com/archives/CKG9NG77W/p1563272044003000

**Comment by johba37** [comment]
we just thought up this together with @micheleb :
<img width="500" alt="Screen Shot 2019-07-16 at 10 14 30 PM" src="https://user-images.githubusercontent.com/659301/61326494-334e6280-a817-11e9-9754-83e6519c2f8e.png">

**Comment by TimDaub** [comment]
Great UI mockups! Shall we create a proper issue for those to implement them after the Ethereum meetup?


For the worker of this issue however, please consider what was written in the original description:

> Note that for the purpose of testing the game at the Ethereum Meetup, a complicated time-series data plot/chart is not required! It's something we can build for ETHBerlinZwei of course. As a countdown requires similar functionality, we recommend not implementing that either (too much work for now).

**Comment by johba37** [comment]
can we still do this on a separate page? i don't see why this needs to be in the wallet.

**Comment by micheleb** [comment]
so right now we have this ![toco2](https://uc7e8d0f059ae1dfa738d45c00af.dl.dropboxusercontent.com/cd/0/inline/AlHiG11d6XmTDfuMhkXA_0xFSPBpQIx0j1Nzl3u4jxOm0Nj2YsESfkQueNpqEHtwrGbifqrlkj9SlgnOMFEOKkQu4P9-kdUSauTkLegRm4V3JQ/file#) using the app inside the `webapp` folder on the [the demo repo](https://github.com/social-dist0rtion-protocol/toco2-demo).

The data is polled every 10 seconds using the `getUnspent()` function iterating over a list of addresses (which is now hardcoded to just @vrde's address, but it should be initialized to the list of addresses of all participants). Names aren't being displayed because... they have not been set in the passports 😅 but as soon as they're set, they will show up on the page. Avatars, not yet, because we need to decide on where to upload user pics and how to link them to the passports.

Data is stored on local storage, so the page can be reloaded without losing anything.

The sustainability index is now calculated as `1 / Math.max(1, countryEmissions - countryTrees)` (where `trees` is actually carbon locked), so that higher scores mean better performance (because "lower is better" is always awkward).

The points are all near 0 because we haven't been trading much yet, and because the numbers need to be tuned, anyway. Also, nobody shows up in the tree planting list because no tree has been planted yet. Those two lists show the top 10 scorers for each category.
