### ISSUE TITLE
Handshaking can lead to sudden end of game

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#38]

**Comment by vrde** [comment]
# Scope
- Right now anyone can handshake as much as they want with anyone else.
- This behavior can produce a huge amount of CO₂ and lead to the sudden end of the game just because two players decide to ruin the game for anyone else.
- Nothing stops a player to write a bot to handshake for them forever.
- Consider that the game will be played by experts so client side solutions can be easily bypassed.

# Deliverables
- A way to "rate limit" handshaking with the same player.

# Roles
- Bounty gardener: @vrde / 10%
- Bounty worker: ? / 75%
- Bounty reviewer: ? / 15%

**Comment by johba37** [comment]
**option A:** still implement it on the client side 😁  writing a script to handshake and explode the planet is not alligned with the interests of any-one, as swag becomes infinitely expensive.

**option B:** Store in the passport whom the user handshaked with using a merkle tree and proof structures.

**Comment by vrde** [comment]
going for option A

**Comment by vrde** [comment]
Depends on #68
